project:
  type: website
  output-dir: docs

website:
  title: "Jack Bailey"
  site-url: https://www.jack-bailey.co.uk
  description: "Dr Jack Bailey, Political Scientist"
  google-analytics: "G-M077RNV9CB"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: http://github.com/jackobailey
      - icon: twitter
        href: https://twitter.com/PoliSciJack
      - icon: linkedin
        href: https://www.linkedin.com/in/jack-bailey-776221227/
      - icon: rss
        href: index.xml
  # twitter-card:
  #   image: thumbnail_blog.png
  #   card-style: summary_large_image
  #   creator: "@PoliSciJack"
format:
  html:
    theme:
      - united
      - custom.scss
    mainfont: Cabin
    fontcolor: "#111111"
    css: styles.css

editor: visual

